# Generated by Django 5.0 on 2025-02-08 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sets", models.IntegerField(default=3)),
                ("reps", models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("day", models.CharField(max_length=20)),
                ("time", models.TimeField()),
            ],
        ),
    ]
